### ISSUE TITLE
Two separate images directories

### ISSUE THREAD

**Issue by V0XNIHILI** [harvard-edge/cs249r_book#105]
Currently, there are two different image directories in the root of this project:

<img width="341" alt="image" src="https://github.com/harvard-edge/cs249r_book/assets/24796206/3680e70d-5de4-4354-aeed-8a45878fc061">

@profvjreddi would you be okay if I move the `images_ml_frameworks` directory into the main `images` folder?

**Comment by profvjreddi** [comment]
Hi @V0XNIHILI - yes, please go ahead and do that.

**Comment by profvjreddi** [comment]
One thing we should do is to create a chapter for each folder and keep all relevant content under that folder. 

E.g. `optimizations.qmd` goes into `optimizations/optimizations.qmd` and there is a folder for images like `optimizations/images/`. 

We have an issue with that https://github.com/harvard-edge/cs249r_book/issues/22

**Comment by profvjreddi** [comment]
This is addressed in the big merge I did here: 3625af9cc4bfbc5e4f6e1eb9272b11d008825164
