### ISSUE TITLE
Bold text in subsection intro?

### ISSUE THREAD

**Issue by V0XNIHILI** [harvard-edge/cs249r_book#125]
In 10.3.4, there is some bold part in the intro of the section:

<img width="600" alt="image" src="https://github.com/harvard-edge/cs249r_book/assets/24796206/39f3787c-e7a4-4c97-85f3-537790f59f90">

However, as far as I can see, this is only done here. Should we keep this or remove it?

**Comment by profvjreddi** [comment]
Thanks - fixed here 3b575367bfa97ed825b72baf34148178a59e56fb
(figured it is faster for me to just resolve it than us going back and forth)
