### ISSUE TITLE
Missing image in efficient AI chapter

### ISSUE THREAD

**Issue by V0XNIHILI** [harvard-edge/cs249r_book#126]
<img width="591" alt="image" src="https://github.com/harvard-edge/cs249r_book/assets/24796206/d2742b37-3349-4831-972a-f5621c83a2dd">

Line in which this image appears: https://github.com/harvard-edge/cs249r_book/blob/a9c95931740015d893def57b39ff52f86ddd0488/contents/efficient_ai/efficient_ai.qmd#L39C30-L39C153

**Comment by profvjreddi** [comment]
Thanks for catching it. Fixed with cc443e321b48ec66556d3ffcc64e48cd129d37ec
