### ISSUE TITLE
Chapter 14. AIOps refers to AI for IT Operations

### ISSUE THREAD

**Issue by bogatinovskijasmin** [harvard-edge/cs249r_book#132]
AIOps is a whole research discipline dedicated to the idea of using AI methods to improve the IT operations of computer systems. The title of chapter 14 is missaligned. Consider renaming it.

**Comment by profvjreddi** [comment]
Thank you for your feedback, @bogatinovskijasmin! Such feedback is timely! 

Could you provide some suggestions? Specifically, the chapter is circling around things related to MLOps and a bit beyond.

**Comment by profvjreddi** [comment]
Resolved this in the latest build -- [;dev](https://harvard-edge.github.io/cs249r_book_dev/) -- that I will push to `main` in a few days.
