### ISSUE TITLE
Resourses: Book by Ashish Vaswani link is broken

### ISSUE THREAD

**Issue by Mjrovai** [harvard-edge/cs249r_book#136]
[Deep Learning on Microcontrollers: Learn how to develop embedded AI applications using TinyML](https://www.amazon.com/Deep-Learning-Microcontrollers-Applications-Embedded/dp/1803234378/) by Ashish Vaswani

**Comment by profvjreddi** [comment]
Thanks for catching that, I removed it for now - 44e1067ea622ac3f4c4f2a8c4299a1316c29e194

**Comment by profvjreddi** [comment]
Thanks for catching that, I removed it for now - https://github.com/harvard-edge/cs249r_book/commit/44e1067ea622ac3f4c4f2a8c4299a1316c29e194
