### ISSUE TITLE
References.qmd

### ISSUE THREAD

**Issue by profvjreddi** [harvard-edge/cs249r_book#137]
I had to remove references.qmd which would compile one long list of references from all the smaller `.bib` files. The references also don't render at the bottom of the document, only at the end. It would be nice to resolve this issue.

**Comment by profvjreddi** [comment]
@uchendui is it possible to create a github action that builds a single references.bib file from all the .bib files found in the contents/ directory so that we can then use that to build  the PDF?

**Comment by uchendui** [comment]
Yes, that should be possible! I can search around for some existing solutions for combining code files

**Comment by profvjreddi** [comment]
This was resolved with an update to Quarto 1.4.0 version as they added support for this.
