### ISSUE TITLE
Windows 10 renderization problemns

### ISSUE THREAD

**Issue by ilejarza** [harvard-edge/cs249r_book#139]
While rendering with Quarto, on a Windows 10 system, the following issuues were found:

'******************** ' is a way to separate issues

PS C:\Users\IRLO\cs249r_book-main> quarto render
[ 1/39] index.qmd
******************** 
[12/39] contents\data_engineering\data_engineering.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\data_engineering\nbsp; https:\doi.org\10.48550\arXiv.2103.14749 arXiv-issued DOI via DataCite'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\data_engineering\nbsp; https:\doi.org\10.48550\arXiv.2103.14749 arXiv-issued DOI via DataCite'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:492:14)
    at inputTargetIndex (file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:83490:10)
    at resolveInputTarget (file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:83583:25)
    at file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:93022:55
    at async file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:81203:33
    at async withTimingAsync (file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:19633:25)
    at async runHtmlPostprocessors (file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:81196:9)
    at async Object.complete (file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:81073:43)
    at async Object.onPostProcess (file:///C:/Users/IRLO/AppData/Local/Programs/Quarto/bin/quarto.js:98888:36)
******************** 
[16/39] contents\optimizations\optimizations.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\ieeexplore.ieee.org\document\5197422](https:\ieeexplore.ieee.org\document\5197422)'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\ieeexplore.ieee.org\document\5197422](https:\ieeexplore.ieee.org\document\5197422)'
******************** 
[16/39] contents\optimizations\optimizations.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1602.07360](https:\arxiv.org\abs\1602.07360)'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1602.07360](https:\arxiv.org\abs\1602.07360)'
******************** 
[16/39] contents\optimizations\optimizations.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1704.04861](https:\arxiv.org\abs\1704.04861)'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1704.04861](https:\arxiv.org\abs\1704.04861)'
******************** 
[16/39] contents\optimizations\optimizations.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1905.11946](https:\arxiv.org\abs\1905.11946)'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1905.11946](https:\arxiv.org\abs\1905.11946)'
******************** 
[16/39] contents\optimizations\optimizations.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1711.06798](https:\arxiv.org\abs\1711.06798)'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\arxiv.org\abs\1711.06798](https:\arxiv.org\abs\1711.06798)'
******************** 
[16/39] contents\optimizations\optimizations.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\www.tensorflow.org\lite](https:\www.tensorflow.org\lite)'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\www.tensorflow.org\lite](https:\www.tensorflow.org\lite)'
******************** 
[16/39] contents\optimizations\optimizations.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\www.keil.com\pack\doc\CMSIS\NN\html\index.html](https:\www.keil.com\pack\doc\CMSIS\NN\html\index.html)'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\optimizations\[https:\www.keil.com\pack\doc\CMSIS\NN\html\index.html](https:\www.keil.com\pack\doc\CMSIS\NN\html\index.html)'
******************** 
[23/39] contents\sustainable_ai\sustainable_ai.qmd
ERROR: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\sustainable_ai\@https:\www.computerworld.com\article\3431148\why-data-centres-are-the-new-frontier-in-the-fight-against-climate-change.html'

Error: El nombre de archivo, el nombre de directorio o la sintaxis de la etiqueta del volumen no son correctos. (os error 123), stat 'C:\Users\IRLO\cs249r_book-main\contents\sustainable_ai\@https:\www.computerworld.com\article\3431148\why-data-centres-are-the-new-frontier-in-the-fight-against-climate-change.html'

Thanks for your attention!!

**Comment by msesboue** [comment]
Hi, 

I have a similar issue on Windows 11 (by similar I mean starting when rendering the 12th section):

```
quarto render
A new release of Deno is available: 1.28.2 → 1.39.0 Run `deno upgrade` to install it.
[ 1/39] index.qmd
[ 2/39] contents\dedication.qmd
[ 3/39] contents\acknowledgements.qmd
[ 4/39] contents\contributors.qmd
[ 5/39] contents\copyright.qmd
[ 6/39] contents\about.qmd
[ 7/39] contents\introduction.qmd
[ 8/39] contents\embedded_sys\embedded_sys.qmd
[ 9/39] contents\dl_primer\dl_primer.qmd
[10/39] contents\embedded_ml\embedded_ml.qmd
[11/39] contents\workflow\workflow.qmd
[12/39] contents\data_engineering\data_engineering.qmd
ERROR: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. (os error 123), stat 'C:\Users\msesboue\Documents\readings\books\cs249r_book\contents\data_engineering\nbsp; https:\doi.org\10.48550\arXiv.2103.14749 arXiv-issued DOI via DataCite'

Error: La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte. (os error 123), stat 'C:\Users\msesboue\Documents\readings\books\cs249r_book\contents\data_engineering\nbsp; https:\doi.org\10.48550\arXiv.2103.14749 arXiv-issued DOI via DataCite'
    at Object.lstatSync (deno:runtime/js/30_fs.js:305:9)
    at existsSync (file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:492:14)
    at inputTargetIndex (file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:83490:10)
    at resolveInputTarget (file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:83583:25)
    at file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:93022:55
    at async file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:81203:33
    at async withTimingAsync (file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:19633:25)
    at async runHtmlPostprocessors (file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:81196:9)
    at async Object.complete (file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:81073:43)
    at async Object.onPostProcess (file:///C:/Users/msesboue/AppData/Local/Programs/Quarto/bin/quarto.js:98888:36)
```
    
I hope it helps, and thank you so much for this awesome resource :)

**Comment by profvjreddi** [comment]
@msesboue and @ilejarza could you folks please try now that the issue has been resolved?

**Comment by msesboue** [comment]
Thank so much @profvjreddi, it now works perfectly on my side.

**Comment by profvjreddi** [comment]
Awesome @msesboue - the credit goes to @Naeemkh for fixing it :) Thanks @Naeemkh!

**Comment by ilejarza** [comment]
Nice, smooth and easy. Thank you very much, Vijay!

**Comment by ilejarza** [comment]
Thanks to Naeem too!
