### ISSUE TITLE
cover_efficient_ai.png is missing

### ISSUE THREAD

**Issue by Mjrovai** [harvard-edge/cs249r_book#147]
./images/png/cover_efficient_ai.png is missing for Efficient AI chapter

**Comment by profvjreddi** [comment]
That's odd, I see it here: 

`$ find . -name "cover_efficient_ai*"` gives me `./_book/contents/efficient_ai/images/png/cover_efficient_ai.png`

**Comment by profvjreddi** [comment]
Oh oops, now I see the issue. It renders for me but it doesn't actually exist in the right contents directory!
