### ISSUE TITLE
Incorrect program link in the "Testing the ToF (Time of Flight) Sensor" section

### ISSUE THREAD

**Issue by mouseart** [harvard-edge/cs249r_book#165]
I noticed an inconsistency in the "[Testing the ToF (Time of Flight) Sensor](https://harvard-edge.github.io/cs249r_book/contents/niclav_sys/niclav_sys.html#testing-the-tof-time-of-flight-sensor)" section of your document. The text mentions installing the VL53L1X library in the Arduino IDE and running a sketch named proximity_detection.ino. However, the provided link https://github.com/Mjrovai/Arduino_Nicla_Vision/blob/main/Micropython/distance_image_meter.py leads to a MicroPython program distance_image_meter.py intended for use with the OpenMV camera.

The linked program does not match the description in the document, which specifically refers to an Arduino sketch named proximity_detection.ino. I searched for proximity_detection.ino on GitHub but could not find any relevant results.

Could you please review this section and update the link to point to the correct Arduino sketch that demonstrates the usage of the VL53L1X sensor with the Arduino IDE? If the mentioned proximity_detection.ino sketch is not available, it would be helpful to provide a suitable alternative or update the document text to match the linked program.

Thank you for your attention to this matter and for providing clarity to the readers of your document.

Best regards,
Leon Feng

**Comment by profvjreddi** [comment]
Thank you @mouseart for the feedback! Really appreciate it. @Mjrovai can you please take a look at this?

**Comment by Mjrovai** [comment]
Thank you, Leon. 
The correct link for using the sensor with Arduino IDE is:
https://github.com/Mjrovai/Arduino_Nicla_Vision/blob/main/Arduino-IDE/proximity_detection/proximity_detection.ino

I will update the text properly.
Thanks
Marcelo

**Comment by profvjreddi** [comment]
Thank you @Mjrovai for your fix here: 43d959c0f7a8d8cd3ddaacbb24882509f39dec98
