### ISSUE TITLE
Chapter 4  Embedded AI - Links leading to source are broken

### ISSUE THREAD

**Issue by BrunoScaglione** [harvard-edge/cs249r_book#191]
I wanted to edit a small thing in the chapter, but these links are broken in the chapter's page: 

- [Edit this page](https://github.com/harvard-edge/cs249r_book/edit/main/contents/embedded_ml/embedded_ml.qmd)
- [View source](https://github.com/harvard-edge/cs249r_book/blob/main/contents/embedded_ml/embedded_ml.qmd)

**Comment by profvjreddi** [comment]
@BrunoScaglione There is a discrepancy between the main Git repo and the website, causing the issue. The website shows a relatively old version of what the book really is at in terms of updates. So if you want to update, you will have to checkout the Git repo, and build it locally and make the changes.

**Comment by profvjreddi** [comment]
So if you want to change something now, the file to look at is `ml_systems.qmd`

**Comment by profvjreddi** [comment]
Closed [1373261](https://github.com/harvard-edge/cs249r_book/commit/1373261cbf809e8c2b5a0222999830f42967fe07)
