### ISSUE TITLE
Re-structure chapters -> folders

### ISSUE THREAD

**Issue by profvjreddi** [harvard-edge/cs249r_book#22]
Need to structure each chapter QMD file as a folder so that we can keep the (1) content and (2) exercises together.

**Comment by V0XNIHILI** [comment]
You are working on this right now, right?

**Comment by V0XNIHILI** [comment]
I think we should not leave [`mvfiles.py`](https://github.com/harvard-edge/cs249r_book/blob/main/mvfiles.py) is the project.

**Comment by profvjreddi** [comment]
I agree @V0XNIHILI - I was in the midst of cleaning it up!

I finished this with @Naeemkh's help on how to structure things. The commit responsible for this is 3625af9cc4bfbc5e4f6e1eb9272b11d008825164 🥳
