### ISSUE TITLE
Minor syntax issue: Section 14.4 has an issue with markdown in text and url highlighting 

### ISSUE THREAD

**Issue by nx6xe23** [harvard-edge/cs249r_book#235]
<img width="1049" alt="image" src="https://github.com/harvard-edge/cs249r_book/assets/81481005/9f1ef0d5-d97d-441e-a7a0-969e4fee2bb8">
There is a minor markdown syntax issue in the PDF and the web version on page 105 in section 14.4.

**Comment by profvjreddi** [comment]
Thanks Anmol 👍 Feel free to issue a PR with the fix if you'd like. I'd appreciate that!
