### ISSUE TITLE
Reader nits : Chapter 7 suggestions

### ISSUE THREAD

**Issue by emmanuel2406** [harvard-edge/cs249r_book#314]
A few nits I picked up while reading this chapter. Please notify me whether this is the right way to propose these changes. 

1. Video 7.1 and 7.2 links do not work/ not added yet
2. Section 7.4.2 : The terms "stratify" and "stratification" should be defined earlier before it's used for unfamiliar readers.
3. Redundancies of paragraphs in section 7.4.2: “No unseen data for final evaluation” is merely describing the need for a final test set and should either be put more forward or removed since it is covered by the paragraph of “reusing the test set multiple times”
4. Section 7.7.2 Dropout : inconsistency with what p refers to. Should be the probability of dropping a node as opposed to keeping it. The Bernoulli trial definition could confuse some readers. 
5. Section 7.9 & 7.8: Activation section introduces some of the core activation functions with their formulae. 7.8 refers to this section quite a bit, and so switching them would make a better order.

**Comment by profvjreddi** [comment]
Thanks @emmanuel2406 we are working through quite a few fixes, so appreciate the feedback. We will push some updates soon.

**Comment by jasonjabbour** [comment]
Thanks Emmanuel! This has been addressed in #349. Closing this issue out.
