### ISSUE TITLE
2 typos in frameworks.qmd

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#346]
In "...\contents\frameworks\frameworks.qmd":
1) The phrase starting with "repository of reusable machine learning model components to allow....." --> missing final dot/point
2) Search for "Tesnor" must be "Tensor"

In "contribute.md":
"Naviage to the repository" --> "**Navigate** to the repository"

**Comment by profvjreddi** [comment]
Thanks @BravoBaldo appreciate it! Will fix it.
