### ISSUE TITLE
Duplicate contributors in "contributors_it"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#359]
In "contributors_it"

- Aghyad Deeb
- Sophia Cho
- Yu-Shun Hsiao

are duplicated.
Is it intentional?

Baldo

**Comment by profvjreddi** [comment]
Thanks for catching this.

@uchendui do you have any idea why this is happening? @Naeemkh as well just for visibility.

**Comment by uchendui** [comment]
Fixed by 2938817.
