### ISSUE TITLE
Slowdown after changing "header-includes.tex"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#372]
Since it was changed
`...\tex\header-includes.tex`
The build slowed down a lot and xelatex runs 10 times (instead of usual 3 times) ending with the message:
"WARN: maximum number of runs (9) reached"

The problem seems to be "\usepackage{titlesec}" and the following "\titleformat..."
I don't know how to fix it :(

**Note:** you don't need "\usepackage{xcolor}" in row 80: it is already in row 17

Baldo

**Comment by BravoBaldo** [comment]
With today's update there are 5 executions instead of 3 but there is no longer the warning message.
I think you can close this.

**Comment by profvjreddi** [comment]
Thanks for letting me know! I used the titlesec to fix an issue with spacing. I will clean up the package, and remove lot and lof which should help.
