### ISSUE TITLE
Spaces and dot in frameworks.qmd

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#383]
In "frameworks.qmd"
Search "`Enable graph optimizations by seeing full model ahead of`"... (is a table)

Please review:
Spaces, and maybe a dot, is required before and after "`Can export and deploy frozen graphs`"

Please check the PDF rendering of all table, similar problems are in the other cells

**Comment by profvjreddi** [comment]
Thanks for catching this. Looks like a handful of them slipped when I updated them.

**Comment by profvjreddi** [comment]
Fixed in 56c500dddf84de97a386e00741e9faa9612a12ba
