### ISSUE TITLE
Last part of "ops.qmd"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#424]
In "ops.qmd",

- In "13.5.1 Data Engineers": I suspect "Provisioning and optimizing data processing systems." must be another pointed paragraph!
- In "13.5.4 DevOps Engineers": "a DevOps"...."They build" (A...they ????)	
- Please review Table "Comparison of Traditional MLOps and Embedded MLOps practices."
- "While understanding the principles is not a substitute for understanding them" --> Can you, please, review this?
- "I will provide a quick overview ..." (It is very rare to find the "first person" in this book!)
- Search "Example: Hugging Face’s Dataset Hub"-- missing dot and/or parenthesis
- "Developers start by UPLOADING their data through file UPLOAD "  Please review
- ...."and improved to improve performance."

**Comment by profvjreddi** [comment]
Thank you for the nitpicks @BravoBaldo -- pushed fixes for these! 🙏
