### ISSUE TITLE
Notes in "privacy_security.qmd"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#431]
In "privacy_security.qmd",

- 	(Please Note: some parts are personal opinions!)
- 	
- 	"analysis for move reviews" ---> "analysis for movIe reviews"
- 	"14.5.3 Fault-injection Attacks", search "skip the `jmp` end instruction" --> must be "skip the `jmp end` instruction" (This is pure nitpicking!!!)
- 	"Researchers could use it to control brakes and other components" --> "An attackers could use it ...."
- 	"In June, a class action lawsuit was"...which year?
- 	"Some researchers demonstrate a real-life" --> "Some researchers have demonstrated a real example" ???
- 	" from occurring and causing any harm" missing final dot (or missed other words!)
- 	Search "multipartymultiparty" is a duplication?
- 	"Optimized hardware and parallelization can HELP but not eliminate this issue." --> (suggestion) "Optimized hardware and parallelization can ALLEVIATE, but not eliminate, this issue."
- 	"The random SPITS ensure" ...maybe outputs ???
- 	The acronym MPC, (which I assume stands for "Multi-Party Communication"), is not explicitly defined anywhere.
- 	Last paragraph before "Summary": "Additional pitfalls of synthetic data include amplified biases, LABELING DIFFICULTIES, ...." In my opinion, labeling is a trivial thing if you are the one generating the sample yourself!

**Comment by profvjreddi** [comment]
Thank you for the feedback! Will fix.

**Comment by profvjreddi** [comment]
I update the labeling one to be mislabeling, cause that does happen. But the other ones are good; some of these mistakes (even across other chapters) are coming from my use of Grammarly to fix mistakes but i had automated some checking, and some clicks got messed up is what I am seeing from some of your edit suggestions. Thanks for catching all these.
