### ISSUE TITLE
Some points in responsible_ai.qmd

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#436]
In "responsible_ai.qmd":
	(Please Note: some parts are personal opinions!)

- 	In "15.5.2 Preserving Privacy", search "Figure XXX"--> missing reference.
- 	Search "models to approximately forget data [?]" why "?"
- 	Search "hospitals are very different"---> why sharp (#) at the end?
- 	Search "and intr."---> what does "intr" stand for?
- 	Please can you change "ility, and fail and redness" may be in "ability, failure, shame" ??? It is not clear to me.
- 	Search "ADS safety" ---> what does "ADS" stand for?
- 	Search "Calvo 2020" maybe you need to remove the year or "Rafael Calvo" or simply "Calvo" (see also next phrase: "They propose...."

Note: Some links are "reserved"... not exactly "free/open" as the book. Example: [Human-Centered AI, Chapter 8 "Government Interventions and Regulations"](https://academic-oup-com.ezp-prod1.hul.harvard.edu/book/41126/chapter/350465542), It could be a problem for non-academic people.

Note2:
In "hw_acceleration.qmd"
	"succintly" or "succinCtly" ??

Baldo

**Comment by profvjreddi** [comment]
Thank you for catching these @BravoBaldo! 🙏 I have fixed all these and pushed an update! 

> * In "15.5.2 Preserving Privacy", search "Figure XXX"--> missing reference.

Thanks, this was an issue during exporting from google docs. Somehow missed linking the reference. Removed it.

> * Search "models to approximately forget data [?]" why "?"

Ah, we missed linking in the reference during Google doc export -- we/I originally wrote everything in Google docs and then exported it to markdown but we had to manually copy over all the references which were in comments, so must have missed this!

> * Search "hospitals are very different"---> why sharp (#) at the end?

Typo.

> * Search "and intr."---> what does "intr" stand for?

Fixed! It was a mistaken with some automated Grammarly checker pass I did a few months ago. Automating grammar checks seems like a bad idea cause you have caught a lot of mistakes over the past several weeks 🙏 


> * Please can you change "ility, and fail and redness" may be in "ability, failure, shame" ??? It is not clear to me.

Fixed, another Grammarly related automation error. 

> * Search "ADS safety" ---> what does "ADS" stand for?

Automated Driving System (ADS)

> * Search "Calvo 2020" maybe you need to remove the year or "Rafael Calvo" or simply "Calvo" (see also next phrase: "They propose...."

Fixed!
