### ISSUE TITLE
Points to review in "sustainable_ai.qmd"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#438]
(Please Note: as always, some parts are personal opinions!)

- Search "important in AI AI's rapid"... maybe a point missed or doubled "AI"
- Search "reduce A. I'm" ???? ---> "reduce AI"
- Search "does not meet requirements," ??? replace comma with dot
- Search "does not directly emit carbon emissions but" ---  "does not directly produce carbon emissions but"
- The caption of "Energy sources and generation capabilities. Source: Energy Charts.." ends with 2 points! (see ..."?l=en&c=DE).](images"...
- Search "a state-of-the-art fab producing state-of-the-art chips"--> obviously a "state-of-the-art" factory produces "state-of-the-art" things!
- "BOD" is never declared, I suppose "Biochemical Oxygen Demand"
- The sentence ending with "but these are ad hoc approaches at best."... perhaps should be revised
- The subsections of "16.11 Embedded AI - Internet of Trash" are not numbered perhaps because they are declared with 4 "#" (e.g. "#### E-waste"). Is this intentional?
- Search "As institutional investors" maybe the whole sentence should have been highlighted somehow but the tags "fail"
- Search "This consists of three components",  maybe the next sentence needs to be revised

Baldo

**Comment by profvjreddi** [comment]
Keep them coming! Thanks @BravoBaldo.
