### ISSUE TITLE
Notes in "ai_for_good.qmd"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#445]
In "ai_for_good.qmd",	
	Search "required to Access basic" ---> "A" in lowercase ?
	Search "tiny chips with processing power, memory, and connectivity." maybe you have to add "limited"
	Search "for source-seeking" maybe you have to add "light" to source ?
	Search "challenge is limited Access" ---> "A" in lowercase ?

**Comment by profvjreddi** [comment]
Thank you @BravoBaldo
