### ISSUE TITLE
Some notes on "Labs"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#449]
(Please Note: as always, some parts are personal opinions!)
	

- In "labs/getting_started.qmd":
	- Suggestion: It might be helpful to add the price, at least to give an idea.
	- About "Raspberry Pi" --> The exact version is not clear... (but I haven't read about the lab yet)
- In "arduino/nicla_vision/object_detection/object_detection.qmd":
	- Search "FOMO (Faster Objects, More Objects) MobileNetV2 0.35" ---> missing initial apex "'" or remove last
- In "arduino/nicla_vision/motion_classification/motion_classification.it.qmd":
	- Search "Classy all" ---> "Classify all"
	- Search "maritime and terrestrial:" and "anomaly detection:" --> both (?) must start with uppercase

- In "seeed/xiao_esp32s3/setup/setup.qmd"
	- Search "uploading.:" --> remove dot ?
	- Search "**turns"	--> remove the 2 "**"

**Comment by profvjreddi** [comment]
Thanks @BravoBaldo will fix them tomorrow. 

@Mjrovai just fyi to keep you posted. I am happy to fix these.
