### ISSUE TITLE
2 notes and 2 warnings

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#463]
In "seeed/xiao_esp32s3/image_classification/image_classification.qmd":
	Search "and 1is" --> "and 1 is" (space)

In "sustainable_ai/sustainable_ai.qmd"
	Search "83x" are you sure?  maybe "83%"

There are 2 warnings, maybe because of the reversal of the captions:
	WARN: contents\dl_primer\dl_primer.html: Unable to resolve crossref @tbl-mlvsdl
	WARN: contents\dl_primer\dl_primer.html: Unable to resolve crossref @fig-ml-dl

**Comment by profvjreddi** [comment]
> Search "83x" are you sure? maybe "83%"

Yeap it is 83x per what they said publicly :)
