### ISSUE TITLE
Bad rendering for some links

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#474]
Please note in the "Index.qmd", under "Book Conventions", you have "[Conventions](./contents/conventions.qmd)",
	but in rendered "Index.html" you have a reference to "./contents/conventions.qmd" instead of "./contents/conventions.html"

	The link under "Contributors": "[here](./contents/contributors.qmd)" is rendered correctly!

(Seen on my local version and to public version: https://mlsysbook.ai/)

Maybe you have to explicitly insert "conventions.qmd" into "_quarto.yml" !
	
PS: Please Note, internal links still refer to .qmd files!

**Comment by BravoBaldo** [comment]
I think you have to change (for example "[here](./contents/contributors.qmd)" with @SomeReference.

Unfortunately, in this example, the title is declared as "{.unnumbered}"... see 
https://forum.posit.co/t/quarto-how-to-cross-reference-unnumbered-book-chapter/136279

**Comment by profvjreddi** [comment]
Hi! Thanks, @BravoBaldo, for the feedback and updates and for pointing out these issues. I have a big deadline tomorrow, so I'm planning to address this early next week. Stay tuned.
