### ISSUE TITLE
Some notes in llm and other generic issues

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#475]
**\contents\privacy_security\privacy_security.qmd**	

- 	Search "\*\* Network Threats:\*\*" --> "\*\*Network Threats:\*\*": (remove space before "N")
- 	Search "Qualcomm Secure Execution Environment", after the link, replace "\*\*A Hardware" with "\*\* A Hardware" (insert a space before "A")

**\contents\labs\raspi\llm\llm.qmd**
- Search "(by Microsoft)/" --> "(by Microsoft)."

- Search "The Meta Llama" the whole was copied from "https://ollama.com/library/llama3.2" adding inappropriate commas. In any case it is not clear to me! It might be useful to explain these terms in the text.

- Bold "\*\*....\*\*" does not works inside formatted text "\`\`\`...\`\`\`":
	- search "\*\*7,000 miles (11,267 kilometers)\*\*."
	- search "\*\*Latitude:\*\*"
	- search "\*\*Longitude:\*\*"
	- search "\*\*Paris\*\*." 4 recurrences
	- search "\*\*Rome\*\*."
	- the problem is known: google "markdown bold inside code block"
		- See also "https://meta.stackexchange.com/questions/243709/nested-formatting-inside-code-block"

- Search "but on September 24, the Llama2:3B is a better choice." wich year?
- Search "every day," --> "every day." (dot)
- Search "19.38" --> "19.83"
- Search "Around 1.9.0 seconds." --> "16 nanoseconds."
- Search "answer to a variable" --> "answer into a variable" ??
- Search "language model interaction (IA)" --> why "IA"? Maybe "LMI"?
- Search "aor" ???  "Agent-Object Relationship (AOR)", "Action-Observation-Reflection"... please clarify/explain
	
	
**.../contents/labs/arduino/nicla_vision/kws/kws.it.qmd**
	search "Create two functions,",,, after 2 rows, replace first star "\*" with "\/"
	after 10 rows, a similar problem, "/\*\*" -> "\/*"

### Please Note:
**In all book replace "\*\*: " with ":** " or "\*\* : " (space after last star)

**Comment by profvjreddi** [comment]
Thank you so much, @BravoBaldo! I am finally back from my pressing deadlines and will focus heavily on the book in the coming months. So please keep that feedback coming. I can't appreciate your time and effort enough!
