### ISSUE TITLE
Problems about "Parts"

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#488]
I would like to highlight 2 problems regarding the "Parts"
In "_quarto.yml" you have some "parts" for example:
"- part: FRONT MATTER"
"- part: MAIN"
"- part: Fundamentals"
...
But an incorrect hierarchy creates problems in Pdf:

For Example
	Part II\nMAIN
	Part III\nFundamentals
Having the same hierarchical level "Part II\nMAIN" appears as something omitted.

Another problem is when you render as EPUB and Word (Docx): As you can read here: 
      https://quarto.org/docs/books/book-structure.html#parts-appendices	
"...When rendering a book with parts to these formats, the parts will be ignored."

Then I suggest a different division and to add explicitily pages for "part"s

What do you think about dividing the book between theory and lab?

**Comment by profvjreddi** [comment]
Thanks for catching this issue. Coincidently, I was also thinking of the same lines: https://github.com/harvard-edge/cs249r_book/issues/493

I agree we should ditch the empty parts. Several others have mentioned this to me. 

> What do you think about dividing the book between theory and lab?

+1 again! I do think building two separate builds makes sense.
