### ISSUE TITLE
Some new issues

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#498]
In /core/benchmarking/benchmarking.qmd 
     "perforamnce" ---> "performance"
	
    "MLPerf Training Benchmark*"
	"DAWNBench*"
	"Fathom*"
	All end with a star. Why?

In contents\core\ops\ops.qmd
	WARN: Unable to resolve link target: contents\core\optimizations\ondevice_learning.qmd
	"[On-device Learning](../optimizations/ondevice_learning.qmd)" ---> "[On-device Learning](../ondevice_learning/ondevice_learning.qmd)"

**Comment by profvjreddi** [comment]
Thank you @BravoBaldo. Issued a PR with these fixes. Thanks so much for catching them quickly.
