### ISSUE TITLE
The notebook of ex 5.5 doesn't exist

### ISSUE THREAD

**Issue by profvjreddi** [harvard-edge/cs249r_book#500]
The notebook of ex 5.5 doesn't exist sir

_Originally posted by @tooniesnguyen in https://github.com/harvard-edge/cs249r_book/issues/493#issuecomment-2453424287_

**Comment by profvjreddi** [comment]
Thanks @tooniesnguyen for letting us know! Will look into it.

**Comment by profvjreddi** [comment]
OK found the issue, will fix it soon!

**Comment by profvjreddi** [comment]
@tooniesnguyen we fixed it, can you please try accessing it again by accessing it from here: https://mlsysbook.ai/contents/data_engineering/data_engineering.html#annotation-methods

**Comment by tooniesnguyen** [comment]
Thank you, sir. It has been working well.
