### ISSUE TITLE
Error in pdf

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#513]
Please review last modifications about pdf version:

```
ERROR:
compilation failed- error
Package pgfkeys Error: I do not know the key '/tcb/enhanced jigsaw' and I am going to ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...', \fi and I am going to ignore it. Perhaps you misspelled it.^^J^^JSee the pgfkeys package documentation for explanation.^^JType  H <return>  for immediate help\@err@


l.1834 ...0mm, colframe=quarto-callout-tip-color-frame, toptitle=1mm, bottomtitle=1mm, bottomrule=.15mm, toprule=.15mm, title=\textcolor{quarto-callout-tip-color}{\faLightbulb}\hspace{0.5em}{Learning Objectives}, breakable, colback=white]

```

**Comment by profvjreddi** [comment]
Thanks @BravoBaldo, I will check now. I made some updates to the LaTeX build, so I might be triggering an issue.

**Comment by profvjreddi** [comment]
just pushed an update to the `dev` branch. Could you please check out the latest commit (a01c15b16905154da7a7f98e490e46ee66907043) and rebuild? It works for me now, and I was able to fix the bug that appeared when I tried to build the full PDF

**Comment by BravoBaldo** [comment]
Ok nowThanks Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Vijay Janapa Reddi ***@***.***> Data: 07/11/24  13:06  (GMT+01:00) A: harvard-edge/cs249r_book ***@***.***> Cc: Baldassarre Cesarano ***@***.***>, Mention ***@***.***> Oggetto: Re: [harvard-edge/cs249r_book] Error in pdf (Issue #513) 
just pushed an update to the dev branch. Could you please check out the latest commit (a01c15b) and rebuild? It works for me now, and I was able to fix the bug that appeared when I tried to build the full PDF
