### ISSUE TITLE
Sub-titles marked as normal text in bold

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#537]
Some (46) titles are simply marked in bold rather than as subtitles.
All marked as 
`** The Text **`

Regex: "`^\*\*.*\*\*$`"

For example
```
**Special data storage considerations for TinyML**
```

```
**Key Concepts**
```

I **suggest**  (please verify) "`#### `"
For example
```
#### Special data storage considerations for TinyML**
#### Key Concepts**
```

**Comment by profvjreddi** [comment]
Thanks for catching these. They have been bothering me forever, but I always pushed off changing them. I finally got motivated to fix them thanks to your issue.
