### ISSUE TITLE
Figure 2.7 is not rendered correctly (dev version only)

### ISSUE THREAD

**Issue by Mjrovai** [harvard-edge/cs249r_book#555]
Figure 2.7: Section overview for Tiny ML is not rendered correctly (dev version only)

**Comment by profvjreddi** [comment]
Hi @Mjrovai -- Thank you for letting me know.

Could you please double check because I've pushed a couple updates recently -- https://harvard-edge.github.io/cs249r_book_dev/contents/core/ml_systems/ml_systems.html#hybrid-ml
