### ISSUE TITLE
Some points in ml_systems and dl_primer.

### ISSUE THREAD

**Issue by BravoBaldo** [harvard-edge/cs249r_book#563]
In `contents/core/ml_systems/ml_systems.qmd`
	"...illustrate how ML paradigms—Cloud, Edge, Mobile, and Tiny ML—interact..." --> "...Cloud, Edge, Mobile, and Tiny—interact..." (remove second "ML"

In `contents/core/dl_primer/dl_primer.qmd`

- 	Search "These three factors" the sentence is repeated.
- 	Search "A bias vector": "...for each layer lf" (Is the final 'f' correct?)
- 	Search "Input Layer Processing" probably should be bold and end with a colon.
 		The same goes for the next two points in the list.
- 	Search "approximately 1,875": why "approximately"? the calculation is exact!
- 	Search "in the layer above it." in the text the layers are represented with a horizontal trend from left to right. "above" is strange, I suggest the "previous".
- 	Search "Figure 3.17." remove last dot

**Comment by profvjreddi** [comment]
Thank you so much, @BravoBaldo, for reviewing the updated chapter.

I really appreciate your thoughtful suggestions—they make the fixes so much easier. Working on long sections can be tedious, especially while juggling the book throughout the day, so your quick and helpful feedback means a lot.

Would you mind taking a look at the new Chapter 4 as well?
