### ISSUE TITLE
Create PR templates

### ISSUE THREAD

**Issue by profvjreddi** [harvard-edge/cs249r_book#68]
We want to have different pull requests for things like code/content etc.

**Comment by profvjreddi** [comment]
@Naeemkh think we are done with this right?

**Comment by Naeemkh** [comment]
@profvjreddi, the book chapter PR is done. We need to add PR template for small fixes or maintaining activities. We close this one.

**Comment by profvjreddi** [comment]
Sounds good, thanks!
