### ISSUE TITLE
Consistency - tinyML / TinyML / embedded ML

### ISSUE THREAD

**Issue by profvjreddi** [harvard-edge/cs249r_book#72]
We should be consistent about the wording we use

**Comment by Naeemkh** [comment]
@profvjreddi, Could you please specify the specific terms or phrases that you would like to be used consistently throughout the book? I will then review and ensure their uniform usage.

**Comment by profvjreddi** [comment]
I made a small pass and updated everything that is tinyML -> TinyML just to be consistent. Did this in 42cb3df545839861e249b4bf496745e07cb85334

**Comment by profvjreddi** [comment]
As for embedded and TinyML I am open for thoughts.

**Comment by profvjreddi** [comment]
Minor fix dbaeef1fc48690e1956bbd561ae0eab80ba986c6
