### ISSUE TITLE
Update all figures to have references and cross-links

### ISSUE THREAD

**Issue by profvjreddi** [harvard-edge/cs249r_book#81]
Currently figures are numbered manually. 

It would be good to auto-reference all of them: https://quarto.org/docs/visual-editor/technical.html#cross-references

**Comment by mpstewart1** [comment]
Resolved with commit 26357a4, just needs to be expanded to the other chapters.

**Comment by profvjreddi** [comment]
@mpstewart1 could you please make sure we update all the chapters with this change?

**Comment by profvjreddi** [comment]
@eliasab16 completed it with https://github.com/harvard-edge/cs249r_book/commit/170f296441d1f7669bc45186902708cafa9e99ea and https://github.com/harvard-edge/cs249r_book/commit/3796f7c944da6bd947a72401865edbb051a4babe
