### ISSUE TITLE
Chapter 20 missing in Introduction chapter

### ISSUE THREAD

**Issue by V0XNIHILI** [harvard-edge/cs249r_book#84]
Here: https://harvard-edge.github.io/cs249r_book/introduction.html

Chapter 20 is missing:
![image](https://github.com/harvard-edge/cs249r_book/assets/24796206/f25fd425-72f9-4ebd-915c-c00ddedd6c4c)

**Comment by profvjreddi** [comment]
Some of these chapters are still works in progress, and I figured we could fix them as the work progresses. I plan to make a pass on them over the Xmas break but also need time to organize and synthesize the outline and material for it.

**Comment by profvjreddi** [comment]
Thank you for catching that @V0XNIHILI. I just updated the introduction to reflect the latest state of the book, I wrote that outline before we actually worked on the content 😄 So now that we have the real outline, we can be on point!

Fixed it in this commit: 0bb642f90a92a44c22ed998e3c9a296208b75759
