### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by V0XNIHILI** [harvard-edge/cs249r_book#92]
This figure does not exist anymore:

<img width="604" alt="image" src="https://github.com/harvard-edge/cs249r_book/assets/24796206/86d325b0-d7ce-49da-93f2-de98a10314b2">

File:

`data_engineering.qmd:224`

**Comment by V0XNIHILI** [comment]
@profvjreddi have you had a chance to look at this issue?

**Comment by profvjreddi** [comment]
I checked and it looks OK and I fixed a commented figure issue in 5770eeabbf841862a9842f19fc50e9d5b0467570

**Comment by profvjreddi** [comment]
I checked and it looks OK and I fixed a commented figure issue in https://github.com/harvard-edge/cs249r_book/commit/5770eeabbf841862a9842f19fc50e9d5b0467570
