### ISSUE TITLE
[WIP] dark mode

### ISSUE THREAD

**Issue by V0XNIHILI** [harvard-edge/cs249r_book#95]
Currently adding dark mode to the website. **Please let me know your preference on the dark themes available in Quarto** (personally, I prefer the Slate theme). Will update the custom SCSS accordingly to change, for example, the red color to be more dark-mode friendly or the color of the top bar.

### Slate theme
![image](https://github.com/harvard-edge/cs249r_book/assets/24796206/2fc3b91c-192e-477b-89e4-849f80495237)

### Darkly theme
![image](https://github.com/harvard-edge/cs249r_book/assets/24796206/04920a06-2b10-4b05-8acb-00c96eca8b8f)

### Cyborg theme
![image](https://github.com/harvard-edge/cs249r_book/assets/24796206/140b5972-c5e4-44d9-b723-40079e8f1aee)

**Comment by profvjreddi** [comment]
Slate looks great @V0XNIHILI - thank you!

**Comment by profvjreddi** [comment]
what needs to be done to enable the dark mode?
